language: cpp

os:
  - windows
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
      - os:       osx
        compiler: gcc

      - os:  osx
        env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

      - os:  osx
        env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
  - export CC=gcc-7 CXX=g++-7

install:
  - |
    mkdir -p ${HOME}/vcpkg
    pushd ${HOME}/vcpkg
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin
    git checkout FETCH_HEAD
    ./bootstrap-vcpkg.sh

script:
  - ./vcpkg install
  - popd
  - mkdir -p build && pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCMAKE_TOOLCHAIN_FILE="${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - ctest --output-on-failure